### ISSUE TITLE
Missing mods

### ISSUE THREAD

**Issue by stndaru** [dickynasje/KambingCompany#3]
Currently missing several **crucial** mods
- https://thunderstore.io/c/lethal-company/p/Isbjorn52/MetalPipe/
- https://thunderstore.io/c/lethal-company/p/Bobbie/MetalRecharging/

**Comment by dickynasje** [comment]
How would this affect to the economic growth of the company?

**Comment by dickynasje** [comment]
as it turns out the metal pipe mod needs to be installed with a folder that is outside of the plugins folder, making it impossible to install, will be closing this now.
