### ISSUE TITLE
Provide link to cracked lethal company in readme

### ISSUE THREAD

**Issue by Ghibranalj** [dickynasje/KambingCompany#5]
People are confused where to get the cracked lethal company. please provide :)

![stupid indian](https://media1.tenor.com/m/uIUJIGlnVXEAAAAd/underw6rld-underworld.gif)

**Comment by dickynasje** [comment]
![359790443_801985391459566_4753554292136123464_n](https://github.com/dickynasje/KambingCompany/assets/43110757/d70cfcdd-8532-4027-b78c-6c5c18e7dd89)

please no
